development: 
  adapter: mysql 
  encoding: utf8 
  database: library_development 
  username: root 
  password: [password] 
  host: localhost 
test: 
  adapter: mysql 
  encoding: utf8 
  database: library_test 
  username: root 
  password: [password] 
  host: localhost 
production: 
  adapter: mysql 
  encoding: utf8 
  database: library_production 
  username: root 
  password: [password] 
  host: localhost 
